name: Test the app

on: [push]

jobs:
  Cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run App
        run: |
          streamlit run streamlit_app.py --server.headless True &

      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          record: true
          start: yarn start
          wait-on: "http://localhost:8501"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          host: localhost
          port: 8501
