name: Cypress Tests

on: [push]

jobs:
  Cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run App
        run: |
          nohup streamlit run streamlit_app.py --server.headless True > /dev/null 2>&1 &

      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          record: true
          browser: chrome
          headed: true
          timeout-minutes: 15
          wait-on: "http://localhost:8501"
          wait-on-timeout: 120
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          host: localhost
          port: 8501
